### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information). Digest: 2898429124

### ISSUE THREAD

**Issue by chillpilllike** [rigby-sh/solace-medusa-starter#100]
Getting this error and when I visit the front end:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2898429124

> solace-medusa-starter@0.0.1 start
> next start -p 8000

  ▲ Next.js 14.2.18
  - Local:        http://localhost:8000

 ✓ Starting...
 ✓ Ready in 1648ms
Error: Failed to fetch data
    at s (/app/.next/server/chunks/1690.js:1:30453)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/app/.next/server/chunks/1690.js:1:30505)
    at async Promise.all (index 1)
    at async C (/app/.next/server/app/[countryCode]/(main)/page.js:1:8342) {
  digest: '2898429124'
}

**Comment by chillpilllike** [comment]
I built it with node 20


FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY . .

# Ensure Corepack is enabled and the package manager is initialized
RUN corepack enable && corepack prepare yarn@stable --activate

# Install dependencies based on the preferred package manager

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.

RUN rm -rf .yarn/cache
RUN yarn install

RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

EXPOSE 8000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["yarn", "start"]

**Comment by chillpilllike** [comment]
<img width="822" alt="Screenshot 2024-11-21 at 10 31 10 pm" src="https://github.com/user-attachments/assets/406efe47-79f2-4c21-a121-78422d6e20b6">

**Comment by chillpilllike** [comment]
I built it with node 18 but still getting this error. can you share the dockerfile you used for this build?

**Comment by chillpilllike** [comment]
▲ Next.js 14.2.18
  - Local:        http://localhost:8000

 ✓ Starting...
 ✓ Ready in 1663ms
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:7110:19)
    at successSteps (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:7081:27)
    at eval (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:1454:83)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Failed to fetch data
    at s (/app/.next/server/chunks/1690.js:1:30458)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/app/.next/server/chunks/1690.js:1:30510)
    at async Promise.all (index 1)
    at async C (/app/.next/server/app/[countryCode]/(main)/page.js:1:8342) {
  digest: '1438441803'
}
Error: Failed to fetch data
    at s (/app/.next/server/chunks/1690.js:1:30458)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/app/.next/server/chunks/1690.js:1:30510)
    at async Promise.all (index 1)
    at async C (/app/.next/server/app/[countryCode]/(main)/page.js:1:8342) {
  digest: '1438441803'
}
Error: Failed to fetch data
    at s (/app/.next/server/chunks/1690.js:1:30458)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/app/.next/server/chunks/1690.js:1:30510)
    at async Promise.all (index 1)
    at async C (/app/.next/server/app/[countryCode]/(main)/page.js:1:8342) {
  digest: '1438441803'
}
Error: Failed to fetch data
    at s (/app/.next/server/chunks/1690.js:1:30458)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l (/app/.next/server/chunks/1690.js:1:30510)
    at async Promise.all (index 1)
    at async C (/app/.next/server/app/[countryCode]/(main)/page.js:1:8342) {
  digest: '1438441803'
}
