### ISSUE TITLE
error "Please set app.keys in config/server.js"

### ISSUE THREAD

**Issue by zzell** [rigby-sh/solace-medusa-starter#96]
I'm seeing the following error during initial setup
I couldn't find any mentions in the documentation about how to set the app.keys for strapi. 

```
npm run develop

> my-strapi@0.1.0 develop
> strapi develop

✔ Cleaning dist dir (8ms)
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (113ms)
✔ Creating admin (198ms)
⠦ Loading Strapi(node:80862) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
(Use `node --trace-warnings ...` to show where the warning was created)
⠧ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                          │
│   Error: Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])                                   │
│   at instantiateMiddleware (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/services/server/middleware.js:13:13)           │
│   at Module.resolveMiddlewares (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/services/server/middleware.js:43:18)       │
│   at registerApplicationMiddlewares                                                                                                                                      │
│   (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/services/server/register-middlewares.js:44:40)                          │
│   at async Object.initMiddlewares (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/services/server/index.js:69:7)          │
│   at async Strapi.bootstrap (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/Strapi.js:365:5)                              │
│   at async Strapi.load (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/core/dist/Strapi.js:315:5)                                   │
│   at async Module.develop (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/strapi/dist/node/develop.js:177:28)                       │
│   at async action (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                         │
│   at async Command.parseAsync (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/commander/lib/command.js:923:5)                               │
│   at async runCLI (/Users/rsukhodolskyi/unicorn-test/solace-medusa-starter-strapi/node_modules/@strapi/strapi/dist/cli/index.js:75:3)                                    │
│                                                                                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by agnwoj99** [comment]
Hello @zzell. You should add such envs to your project:

```
# Server
HOST=0.0.0.0
PORT=1337

# Secrets
APP_KEYS="toBeModified1,toBeModified2"
API_TOKEN_SALT=tobemodified
ADMIN_JWT_SECRET=tobemodified
TRANSFER_TOKEN_SALT=tobemodified
JWT_SECRET=tobemodified

# Database
DATABASE_URL=tobemodified
DATABASE_CLIENT=tobemodified
DATABASE_HOST=tobemodified
DATABASE_PORT=tobemodified
DATABASE_NAME=tobemodified
DATABASE_USERNAME=tobemodified
DATABASE_PASSWORD=tobemodified
DATABASE_SSL=false

# Storage
DO_SPACE_PATH=tobemodified
DO_SPACE_ACCESS_KEY=tobemodified
DO_SPACE_SECRET_KEY=tobemodified
DO_SPACE_REGION=tobemodified
DO_SPACE_ENDPOINT=tobemodified
DO_SPACE_BUCKET=tobemodified
SPACE_URL=tobemodified

```

If you have trouble putting this up directly from our repository, create a Strapi instance and import our configuration files:  [Download config file](https://solace-medusa-starter-storage.fra1.cdn.digitaloceanspaces.com/strapi-config.tar.gz)

I hope my answer was helpful!

**Comment by KamilNahotko** [comment]
@fuxianwei @zzell The reason you don’t have any data after the import is that if you are using a new Strapi instance, you’re missing the required content-types. To fix this, you need to use our Strapi instance, which has the correct content-types already set up. After that, you can use our import file to populate the content correctly.

As for the images, Strapi’s documentation states:

`Media from a 3rd party provider (e.g., Cloudinary or AWS S3) are not included in the export as those files do not exist in the upload folders.`

This means we cannot export images stored on external providers like S3. However, we have provided access to the images via Google Drive. You can download them using this link and manually add them back into your Strapi instance: [[Google Drive Link](https://drive.google.com/drive/folders/1FU2KZD74An-JDsRPjTi7BGCgXycXCVyC?usp=sharing)].

Additionally, I am attaching a new data import file that I have tested, and it should work correctly with our Strapi instance.
[[strapi-export.tar.gz](https://github.com/user-attachments/files/18005300/strapi-export.tar.gz)]

If everything is clear and no further assistance is needed, I will close this issue.
